services:
  otel-collector:
    image: ${OTEL_COLLECTOR_CONTRIB_IMAGE}
    container_name: otel-collector
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
    command: [ "--config=/etc/config.yml"]
    user: 0:0
    volumes:
      - ${HOST_FILESYSTEM}:/hostfs:ro
      - ${OTEL_COLLECTOR_CONFIG}:/etc/config.yml
    network_mode: host
    env_file:
      - .env
